# Generated by Django 5.2 on 2025-07-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("author", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("Genere", models.CharField(max_length=20)),
                ("image", models.ImageField(upload_to="books/%y/%m/%d/")),
                ("is_new", models.BooleanField(default=False)),
                ("is_popular", models.BooleanField(default=False)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
