# Generated by Django 5.2 on 2025-07-21 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="Genere",
            new_name="genre",
        ),
    ]
