# Generated by Django 5.2 on 2025-07-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0003_category_remove_book_genre_book_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Genre"},
        ),
        migrations.RemoveField(
            model_name="book",
            name="category",
        ),
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(
                default="books/default_ico/default.png", upload_to="books/%y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.ManyToManyField(related_name="books", to="Main.category"),
        ),
    ]
