# Generated by Django 5.2 on 2025-07-23 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0004_alter_book_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="added_date",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
