# Generated by Django 5.2 on 2025-07-23 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0005_book_added_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["-added_date"]},
        ),
        migrations.AddField(
            model_name="book",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="added_date",
            field=models.DateField(default=datetime.date(2025, 7, 23)),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
