# Generated by Django 5.2 on 2025-07-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0006_alter_book_options_book_slug_alter_book_added_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="slug",
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
