# Generated by Django 5.2 on 2025-07-26 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0008_alter_book_added_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="isbn",
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="added_date",
            field=models.DateField(default=datetime.date(2025, 7, 26)),
        ),
    ]
