# Generated by Django 5.2 on 2025-07-31 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0009_book_isbn_alter_book_added_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="added_date",
            field=models.DateField(default=datetime.date(2025, 7, 31)),
        ),
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="books/%y/%m/%d/"),
        ),
    ]
